import { manifest, type ImageKey, type ImageVariant } from '../assets/manifest';
import { computeUnitRect, type UnitRect } from '../core/stage';

/**
 * Real art from the manifest (generated by `npm run assets`), as a `<picture>`: AVIF first,
 * WebP otherwise, each at 1× and 2×. The browser picks the file from `sizes`, the width the
 * image is drawn at, which this module keeps up to date as the window changes, so a small
 * window or a 1× screen never downloads the big file and a large 2× screen gets it.
 */

/** How wide an image is drawn, in CSS px, for a given window and unit box. */
export type DrawnWidth = (window: { width: number; height: number }, unit: UnitRect) => number;

/** Drawn as `refWidth` unit px wide (anything inside the unit). */
export const unitShare =
  (refWidth: number, unitWidth: number): DrawnWidth =>
  (_, unit) =>
    (unit.width * refWidth) / unitWidth;

export interface Art {
  /** Put this in the DOM (it lays out as if it were the `<img>`). */
  el: HTMLPictureElement;
  img: HTMLImageElement;
  key: ImageKey;
}

const all: { art: Art; width: DrawnWidth }[] = [];

const srcset = (variants: readonly ImageVariant[]): string =>
  variants.map((v) => `${v.src} ${v.width}w`).join(', ');

function updateSizes(): void {
  const win = { width: window.innerWidth, height: window.innerHeight };
  const unit = computeUnitRect(win.width, win.height);
  for (const { art, width } of all) {
    const sizes = `${Math.ceil(width(win, unit))}px`;
    for (const el of [art.img, ...art.el.querySelectorAll('source')]) {
      if (el.getAttribute('sizes') !== sizes) el.setAttribute('sizes', sizes);
    }
  }
}

let listening = false;

export function createArt(key: ImageKey, className: string, width: DrawnWidth): Art {
  const entry = manifest[key];
  const picture = document.createElement('picture');
  picture.className = 'art';

  const avif = document.createElement('source');
  avif.type = 'image/avif';
  avif.srcset = srcset(entry.avif);

  const img = document.createElement('img');
  img.className = className;
  img.alt = '';
  img.draggable = false;
  img.width = entry.width;
  img.height = entry.height;
  img.srcset = srcset(entry.webp);
  const [fallback] = entry.webp;
  if (fallback) img.src = fallback.src;

  picture.append(avif, img);
  const art: Art = { el: picture, img, key };
  all.push({ art, width });
  updateSizes();
  if (!listening) {
    listening = true;
    window.addEventListener('resize', updateSizes);
  }
  return art;
}

/** Every art image created so far, for the preloader. */
export function allArtImages(): HTMLImageElement[] {
  return all.map(({ art }) => art.img);
}
