// Builds the runtime images from the owner's raw exports.
//   assets-src/<name>.png  →  public/assets/<name>@2x.{webp,avif} (source size)
//                             public/assets/<name>@1x.{webp,avif} (half size)
// and writes src/assets/manifest.ts with each image's intrinsic size and file sizes.
// Run with `npm run assets` after changing anything in assets-src/.
import { mkdir, readdir, rm, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import * as prettier from 'prettier';
import sharp from 'sharp';

const ROOT = path.resolve(import.meta.dirname, '..');
const SRC = path.join(ROOT, 'assets-src');
const OUT = path.join(ROOT, 'public/assets');
const MANIFEST = path.join(ROOT, 'src/assets/manifest.ts');
const PUBLIC_PATH = '/assets';

/**
 * One entry per runtime image. `key` is the name used in code. Quality is per image:
 * the screen texture sits at 32% in overlay, so it can be compressed much harder.
 */
const IMAGES = [
  { key: 'background', file: 'bg-room.png', webp: 84, avif: 62 },
  { key: 'frame', file: 'frame.png', webp: 90, avif: 72 },
  { key: 'doorLeft', file: 'door_left.png', webp: 86, avif: 64 },
  { key: 'doorRight', file: 'door_right.png', webp: 86, avif: 64 },
  { key: 'screenTexture', file: 'screen-texture.png', webp: 60, avif: 44 },
];

const FORMATS = ['webp', 'avif'];

async function encode(input, format, quality, outFile) {
  const pipeline =
    format === 'webp'
      ? input.webp({ quality, alphaQuality: 90, effort: 6, smartSubsample: true })
      : input.avif({ quality, effort: 5 });
  await pipeline.toFile(outFile);
  return (await stat(outFile)).size;
}

async function main() {
  const available = new Set(await readdir(SRC));
  await rm(OUT, { recursive: true, force: true });
  await mkdir(OUT, { recursive: true });
  await mkdir(path.dirname(MANIFEST), { recursive: true });

  const entries = [];
  for (const image of IMAGES) {
    if (!available.has(image.file)) throw new Error(`Missing assets-src/${image.file}`);
    const source = sharp(path.join(SRC, image.file));
    const { width, height } = await source.metadata();
    const stem = path.parse(image.file).name;
    const entry = { key: image.key, width, height, files: {}, bytes: {} };

    for (const density of [2, 1]) {
      const w = Math.round(width / (2 / density));
      const h = Math.round(height / (2 / density));
      for (const format of FORMATS) {
        const name = `${stem}@${density}x.${format}`;
        const resized = sharp(path.join(SRC, image.file)).resize(w, h, { kernel: 'lanczos3' });
        const quality = image[format];
        const bytes = await encode(resized, format, quality, path.join(OUT, name));
        entry.files[`${format}${density}x`] = { src: `${PUBLIC_PATH}/${name}`, width: w };
        entry.bytes[`${format}${density}x`] = bytes;
      }
    }
    entries.push(entry);
  }

  const kb = (n) => `${(n / 1024).toFixed(0)} KB`;
  console.log('image            webp@2x   webp@1x   avif@2x   avif@1x');
  const totals = { webp2x: 0, webp1x: 0, avif2x: 0, avif1x: 0 };
  for (const e of entries) {
    console.log(
      e.key.padEnd(16),
      ...Object.keys(totals).map((k) => {
        totals[k] += e.bytes[k];
        return kb(e.bytes[k]).padStart(9);
      }),
    );
  }
  console.log('total'.padEnd(16), ...Object.keys(totals).map((k) => kb(totals[k]).padStart(9)));

  const lines = entries.map((e) => {
    const variant = (k) => `{ src: '${e.files[k].src}', width: ${e.files[k].width} }`;
    return [
      `  ${e.key}: {`,
      `    width: ${e.width},`,
      `    height: ${e.height},`,
      `    webp: [${variant('webp1x')}, ${variant('webp2x')}],`,
      `    avif: [${variant('avif1x')}, ${variant('avif2x')}],`,
      `    bytes: ${JSON.stringify(e.bytes).replaceAll('"', '').replaceAll(':', ': ').replaceAll(',', ', ')},`,
      `  },`,
    ].join('\n');
  });
  const ts = `// Generated by \`npm run assets\` (scripts/assets.mjs). Do not edit by hand.

export interface ImageVariant {
  src: string;
  /** Pixel width of this file. */
  width: number;
}

export interface ManifestImage {
  /** Intrinsic size of the source art (the 2× file). */
  width: number;
  height: number;
  /** 1× then 2×. */
  webp: readonly ImageVariant[];
  avif: readonly ImageVariant[];
  bytes: Readonly<Record<'webp2x' | 'webp1x' | 'avif2x' | 'avif1x', number>>;
}

export const manifest = {
${lines.join('\n')}
} as const satisfies Record<string, ManifestImage>;

export type ImageKey = keyof typeof manifest;
`;
  const options = (await prettier.resolveConfig(MANIFEST)) ?? {};
  await writeFile(MANIFEST, await prettier.format(ts, { ...options, filepath: MANIFEST }));
  console.log(`wrote ${path.relative(ROOT, MANIFEST)}`);
}

await main();
