// Generated by `npm run assets` (scripts/assets.mjs). Do not edit by hand.

export interface ImageVariant {
  src: string;
  /** Pixel width of this file. */
  width: number;
}

export interface ManifestImage {
  /** Intrinsic size of the source art (the 2× file). */
  width: number;
  height: number;
  /** 1× then 2×. */
  webp: readonly ImageVariant[];
  avif: readonly ImageVariant[];
  bytes: Readonly<Record<'webp2x' | 'webp1x' | 'avif2x' | 'avif1x', number>>;
}

export const manifest = {
  background: {
    width: 3300,
    height: 1800,
    webp: [
      { src: '/assets/bg-room@1x.webp', width: 1650 },
      { src: '/assets/bg-room@2x.webp', width: 3300 },
    ],
    avif: [
      { src: '/assets/bg-room@1x.avif', width: 1650 },
      { src: '/assets/bg-room@2x.avif', width: 3300 },
    ],
    bytes: { webp2x: 750302, avif2x: 427546, webp1x: 344580, avif1x: 201449 },
  },
  frame: {
    width: 1894,
    height: 1308,
    webp: [
      { src: '/assets/frame@1x.webp', width: 947 },
      { src: '/assets/frame@2x.webp', width: 1894 },
    ],
    avif: [
      { src: '/assets/frame@1x.avif', width: 947 },
      { src: '/assets/frame@2x.avif', width: 1894 },
    ],
    bytes: { webp2x: 106874, avif2x: 99402, webp1x: 47256, avif1x: 33923 },
  },
  doorLeft: {
    width: 2400,
    height: 1600,
    webp: [
      { src: '/assets/door_left@1x.webp', width: 1200 },
      { src: '/assets/door_left@2x.webp', width: 2400 },
    ],
    avif: [
      { src: '/assets/door_left@1x.avif', width: 1200 },
      { src: '/assets/door_left@2x.avif', width: 2400 },
    ],
    bytes: { webp2x: 220694, avif2x: 183733, webp1x: 96248, avif1x: 71458 },
  },
  doorRight: {
    width: 2400,
    height: 1600,
    webp: [
      { src: '/assets/door_right@1x.webp', width: 1200 },
      { src: '/assets/door_right@2x.webp', width: 2400 },
    ],
    avif: [
      { src: '/assets/door_right@1x.avif', width: 1200 },
      { src: '/assets/door_right@2x.avif', width: 2400 },
    ],
    bytes: { webp2x: 225360, avif2x: 188692, webp1x: 97736, avif1x: 73003 },
  },
  screenTexture: {
    width: 2048,
    height: 1358,
    webp: [
      { src: '/assets/screen-texture@1x.webp', width: 1024 },
      { src: '/assets/screen-texture@2x.webp', width: 2048 },
    ],
    avif: [
      { src: '/assets/screen-texture@1x.avif', width: 1024 },
      { src: '/assets/screen-texture@2x.avif', width: 2048 },
    ],
    bytes: { webp2x: 252028, avif2x: 109664, webp1x: 123070, avif1x: 54705 },
  },
} as const satisfies Record<string, ManifestImage>;

export type ImageKey = keyof typeof manifest;

/** The metal system cursors, 1× and 2× PNG (hotspots in `layout.systemCursor`). */
export const cursorFiles = {
  default: {
    x1: '/assets/cursors/cursor-default.png',
    x2: '/assets/cursors/cursor-default@2x.png',
  },
  pointer: {
    x1: '/assets/cursors/cursor-pointer.png',
    x2: '/assets/cursors/cursor-pointer@2x.png',
  },
  pointerDown: {
    x1: '/assets/cursors/cursor-pointer-down.png',
    x2: '/assets/cursors/cursor-pointer-down@2x.png',
  },
  notAllowed: {
    x1: '/assets/cursors/cursor-not-allowed.png',
    x2: '/assets/cursors/cursor-not-allowed@2x.png',
  },
} as const satisfies Record<string, { x1: string; x2: string }>;

export type CursorKey = keyof typeof cursorFiles;
